version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - '6000:6000'
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start

  test:
    build:
      context: .
    command: yarn test  # Run tests
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
